### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by thecubed** [CyboLabs/Open_Bump#1]
Hey Cybojenix!
Thanks for posting LG's key publicly. You can't actually open source this, considering it contains stolen code from LG.

**Comment by dazjo** [comment]
poo

**Comment by antdking** [comment]
it's hardly stolen if it's in plain text in the bootloader.
LG should really think about their security if someone like me (who does next to no hex editing) can find their public key.

**Comment by thecubed** [comment]
Someone like you can only find their key after someone like us does all the hard work for you. You really think that you would have found it if it wasn't for my team's hard work? I doubt it.

**Comment by dazjo** [comment]
dont be stressin bae

**Comment by antdking** [comment]
and I credited you on the magic bytes.
I'm sorry for managing to figure out the rest, but tbh it was only a matter of time before people started saying that you only needed the first 16 bytes. I already suspected it from the start, but never got round to testing it this morning. But instead of just entirely ripping you off, I decided to try to work it out for myself.

I got pretty far. Maybe someone will finish it off and find out about the magic.

**Comment by thecubed** [comment]
Ha, credit would have been not releasing this.
How would you feel if someone cloned your hard work and then decided to stomp on you publicly?
Pretty crappy and low of you.

But hey, you feel better now that it's open source. You can ride that pony until it dies, open source for the win! You definitely know what's best for the community. You deserve a friggin medal!

**Comment by antdking** [comment]
maybe you can give a better argument as to why you're stat collecting, other than "stats".

This wouldn't have been done if you weren't so vague about how it was done. Now at least the reputable teams can actually use bump.

You knew it was going to be figured out by someone else.

accusing me of blackmail is also not on. I never black mailed you. I simply stated that I was going to open source it. No objection was made whatsoever.

**Comment by thecubed** [comment]
As we stated, the only thing we collect is a username/hash of password (hashed with PBKDF2 so not even we can reverse it)/email address.

Each Bump only collected the sha1sum of the image and we appended the developer's ID hash (generated from random bytes) to the block before we encrypted it. This was so we could track abuse of the service.

But again, if you actually took the time to ASK us this on IRC instead of slapping us in the face, we would have told you.

Reputable teams? Ha, no, the Liquid guys were whining and complaining from Day 0 about Bump even before we released it. You didn't do anyone a favor, you merely GUARANTEED that the next OTAs lock the phones and prevent rollback. But at least the G3 is unlocked for now. You get those 15 minutes in the spotlight you desperately wanted.

**Comment by AndroidUser00110001** [comment]
If you were smart enough for someone like yourself (who does next to no hex editing) can find their public key by other's work. Then you should have been smart enough to keep it to yourself so in the future we don't get locked out. Maybe there was a reason that Team Codefire didn't want to open source it. It's not like they were charging for it...

All this did was hurt the community and not help it in anyway. The tools were already provided for people like yourself and others to do what we like to do with our devices.

Think twice before you want to think of yourself as some hero...

**Comment by ta33ers** [comment]
I have been following this on the xda forum, and wound up here, I hope not to piss more of you off, but it sounds to me that there is blame to go all the way around. Why jump down someone's throat, it would seem to me that, it might be better to educate, rather than vilify, you tell him all he had to do was ask, did it ever occur to you he didn't know to ask? I read folks accusing of looking for 15 minutes of fame, did it ever occur to some, the guy was just trying to help? I for one find it hard to look at folks who claim to be adults acting like spoiled brats, taking their ball, and going home. If the thecubed and his crew want to go closed source, go ahead, last I looked it was a free country, but don't trash those of us that believe open source is more about community, education, and openness. Lastly your work is appreciated, and your resources will be missed, but ask yourself, are you leaving for a good reason, or because your feelings are hurt?

**Comment by antdking** [comment]
@ta33ers I did actually give them warning, and when no objection was made I released it

**Comment by ta33ers** [comment]
I don't know what to tell you, I know they said they were holding off on bump for the v410, but never really gave a reason why. I keep wondering why something I spend several hundred dollars on doesn't belong to me, hell I was an apple fanboy for years till they basically told be I could borrow their over priced hardware, but don't you mess with our Free BSD. They good thing about our community is there tend to be others willing to pick up where others leave off.

**Comment by ta33ers** [comment]
Well cybojenix it would appear your posting is closed on the xda forum, I hope you are happy with what you have done you vile snotball, keep up the good work!

**Comment by antdking** [comment]
I think you'll find that I closed it since the comments had gotten out of hand.

Then again it's easy to alienate XDA users by saying "LG weren't going to patch this exploit". Biggest load of bull I've ever seen

**Comment by tectas** [comment]
@cybojenix , at least for me, it's not about the statement, but simply about respect for the work Team Codefire and @thecubed have done. About pachting the exploit, sure, it's just your word against theirs, but you know what? You also can't tell if they really haven't been in contact with LG, but you know what, no matter if they were or not, because of what you've done, it doesn't matter anymore and for what? An official mark for our device at cm, which changes nothing about the quality of the builds, but just the amount of them, because they are done by the build server? You're an selfish idiot. I'm not a fan of Team Codefire myself and how they've handled the whole website stuff (for me, at first a command line tool had been enough, somewhere afterwards the webpage could have been done [yes, I know, with the log in and api key mechanism, it was better the way they did it, but anyways]), but it doesn't matter, they've done the method and they can chose what to share from it and what not. If developers don't show respect to one another at least to some extend, how should this whole thing work. And it's not like they didn't share the method and right to use to anyone for free. And stats, come on, everyone gathers stats, also cm.

**Comment by Youradouche** [comment]
Cybojenix- it wasn't your to release no matter what, what you did was hurt the community way more the support. As thecube said. Please start providing root and unlocks for the majority of phones on the market today. I hope you can, but we all know you can't which is the by you took someone else's work and decided to go against their wishes on it being public. All for Official CM. Wow, think of yourself much.... 

Youradouche

**Comment by dorimanx** [comment]
Hi, i just want to say THANKS for this open source, i build LG G2 kernel, and we must use old junk Jb bootloader to hack our boot.img with tool named loki, only then JB bootloader accept our custom kernel or recovery.
this sucks, and there was no way to solve it, the online BUMP for developer is useless, as i will have to upload my build each time to try some change i made, it's time waste, and was not an option for LG G2.

Now we finally can use KK bootloader and be happy with signed kernel.
I respect all DEVS that worked hard for original BUMP idea, and for OPEN source here.
All we need, we have now. that's all that matter for LG G2 users. :)
LG G2 community solutes you Cybojenix!

**Comment by jyriprans** [comment]
Thank you for this cybojenix!

**Comment by chevycam94** [comment]
I have to say that @thecubed is justified in his side of the argument.  I follow the PS3 hacking scene as well, and its MUCH better for the end user (who wants hacks), to keep those secrets hidden from "open source".  The Vita also suffered recently because someone leaked a native exploit that was used to run TN-V.  Of course, we were lucky to have someone they post up their exploit for the old build of webkit, which has made a LOT of progress.

But bottom line, DONT open your mouth if you find a root method, unlock method, or other functional security bypass.  If you want to release a pre-bumped recovery, or kernel, thats fine, but keep the METHOD to yourself.  Everyone knows that every company has some employees on all the forums, "watching" what we do, hoping someone slips up and shares a hack or method.  Yes, they are among us.  Its a spy game, and thats the reason we are only a small step ahead of them.  Make sure this is a lesson learned!

**Comment by ta33ers** [comment]
chevycam94 thanks for the response, at least from you I learn something. What I still don't understand is all the foaming at the mouth, thrashing on the floor, tantrums I see. Before your post I would have probably done the same thing and posted a hack if I had found one, and I certainly wouldn't have been looking for a medal. When Linus released Linux to the web, he wasn't looking for fame or fortune, just wanted to share what he had. I my self thank cybojenix, as I have learned a lot here lately.  I still think more can be accomplished through education, and honest critic.

**Comment by chevycam94** [comment]
No problem. :D. Remember, through the right channels, devs can work on such hacks and bypasses, and improve them, without making their methods public. Some secrets are better kept, secret.  The phrase still holds true....good things come to those who wait.
